# Generated by Django 4.2.4 on 2023-09-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20210902_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='address',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=250, null=True),
        ),
    ]
